#!/usr/bin/env python3
"""origin_triage.py — the detector CLI.

Implements the rule frozen in `frozen_metric.json` verbatim: Jev
`origin_choice` (the 3-way question, verbatim) + a confidence gate at theta, an optional
EditLens-llama cross-check, label set {human, machine, abstain}, and disagreement -> abstain.

Shipping decision (pre-registered, from the final mass test): **EditLens-llama is the primary signal
where it is available, Jev is the advisory/cross-check signal.** Measured reasons: on non-fiction
EditLens-llama reaches AUC 0.957 vs Jev 0.872, and EditLens has human FPR 0.00-0.02 on the
non-fiction corpora; Jev uniquely covers generators EditLens misses (GPT-2, GPT-3 and the fake-paper generator SCIgen, Jev
detection 0.97-1.00 vs EditLens 0.01-0.27), so the two are kept together.

SCOPE LIMITATION, measured, not hypothetical: on **human creative fiction** both detectors fail.
Jev's false-positive rate is 0.92-0.97 (AUC 0.614, near chance) and EditLens-llama's is 0.88-1.00
on professional rewrites of AI drafts, expert rewrites and untouched amateur paragraphs. The CLI cannot
detect that condition from the two signals alone -- in creative prose both agree on "machine" --
so it emits an ADVISORY warning when both signals saturate. The warning threshold is post-hoc and
is reported as advisory, never as a label.

This tool answers ONE question: is this text machine-generated? It deliberately exposes no
quality, polish or "slop" score: those axes were measured to be biased toward machine style
(Jev `quality_score` correlates 0.70 with an independent AI-edit detector, and prefers the raw LLM
draft over the human expert rewrite of it 93.3% of the time). Do not add them back.

Usage
  # single text
  ./origin_triage.py --text "Some text to check."
  ./origin_triage.py --text-file draft.md

  # batch
  ./origin_triage.py --jsonl corpus.jsonl --out verdicts.jsonl        # {"id": ..., "text": ...}
  cat corpus.jsonl | ./origin_triage.py --stdin --out verdicts.jsonl

  # attach precomputed EditLens-llama scores (the primary signal)
  ./origin_triage.py --jsonl corpus.jsonl --editlens-scores el.jsonl --out verdicts.jsonl
  #   el.jsonl rows: {"id": <same id as in corpus.jsonl>, "score": 0.97}

  # replay stored answers offline (no API calls)
  ./origin_triage.py --answers stored.jsonl --out verdicts.jsonl
  #   stored.jsonl rows: {"id": ..., "choice": ..., "confidence": ..., "probabilities": {...}, "editlens_llama": 0.97}

  # rerun every offline reproduction check, no API calls
  ./origin_triage.py --reproduce
  ./origin_triage.py --self-test          # rule replay only

Exit codes: 0 = ran (labels may include "abstain"), 2 = configuration error, 3 = all requests failed,
4 = --strict-model violation (the served model differs from the requested model).
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import statistics
import sys
import threading
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_METRIC = HERE / "frozen_metric.json"

# --- the frozen question, verbatim (identical wording to all stored origin_choice calls) --------
QUESTIONS = {
    "origin_choice": {
        "type": "choice",
        "instructions": "Who most likely wrote this text?",
        "criteria": {"human": "Written by a human",
                     "ai": "Generated by an AI system",
                     "edited": "Written by a human, then substantially edited by an AI system"},
    },
    "machine_like": {"type": "noul",
                     "instructions": "Does this text read as if it was generated by an AI system "
                                     "rather than written by a person?"},
}
DIRECT_ENDPOINT = "https://api.typesafe.ai/v1/systemone"
ZEN_ENDPOINT = "https://opencode.ai/zen/v1/systemone"
UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
      "Chrome/131.0.0.0 Safari/537.36")

# Advisory only; post-hoc, not part of the frozen decision rule.
ADVISORY_EL_SATURATION = 0.90


def load_metric(path: Path) -> dict:
    m = json.loads(path.read_text(encoding="utf-8"))
    ref = m["reference_pool_for_theta"]
    m["theta"] = ref.get("computed_theta", 0.31)
    m["el_cut"] = m["decision_rule"] and m.get("el_cut", 0.5)
    return m


def get_key(endpoint: str) -> str:
    if endpoint == ZEN_ENDPOINT:
        names = ("OPENCODE_KEY", "OPENCODE_API_KEY")
    else:
        names = ("TYPESAFE_KEY", "TYPESAFE_API_KEY")
    for var in names:
        v = os.environ.get(var, "").strip()
        if v:
            return v
    rc = Path.home() / ".bashrc"
    if rc.exists():
        pat = r'^export\s+' + "|".join(names) + r'=(.*)$'
        for line in rc.read_text(encoding="utf-8", errors="ignore").splitlines():
            m = re.match(pat, line.strip())
            if m:
                return m.group(1).strip().strip('"').strip("'")
    raise SystemExit(f"no API key found: set one of {', '.join(names)} (env or ~/.bashrc)")


def call_jev(state: str, key: str, endpoint: str, model: str, ask_machine_like: bool = True,
             timeout: int = 90) -> dict:
    qs = {"origin_choice": QUESTIONS["origin_choice"]}
    if ask_machine_like:
        qs["machine_like"] = QUESTIONS["machine_like"]
    payload = {"model": model, "state": state, "questions": qs}
    headers = {"Authorization": f"Bearer {key}", "Content-Type": "application/json",
               "Accept": "application/json"}
    if endpoint == ZEN_ENDPOINT:
        headers["User-Agent"] = UA          # Cloudflare 1010 otherwise
    req = urllib.request.Request(endpoint, data=json.dumps(payload).encode(), headers=headers)
    delays = (2, 4, 8)
    for attempt in range(len(delays) + 1):
        try:
            with urllib.request.urlopen(req, timeout=timeout) as r:
                d = json.loads(r.read())
            a = d.get("answers") or {}
            oc = a.get("origin_choice") or {}
            return {"ok": True, "model_echo": d.get("model"), "choice": oc.get("choice"),
                    "confidence": oc.get("confidence"),
                    "probabilities": oc.get("probabilities") or {},
                    "machine_like": (a.get("machine_like") or {}).get("noul"),
                    "usage": d.get("usage"), "latency_ms": None, "error": None}
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503, 504, 529) and attempt < len(delays):
                time.sleep(delays[attempt])
                continue
            return {"ok": False, "error": f"HTTP {e.code}", "body": e.read()[:200].decode(errors="ignore")}
        except Exception as e:  # noqa: BLE001
            if attempt < len(delays):
                time.sleep(delays[attempt])
                continue
            return {"ok": False, "error": f"{type(e).__name__}: {e}"}
    return {"ok": False, "error": "exhausted retries"}


def decide(jev: dict, el_score: float | None, theta: float, el_cut: float) -> dict:
    """The frozen decision rule. Jev supplies the call; EditLens (when present) gates it."""
    choice = jev.get("choice")
    conf = jev.get("confidence")
    probs = jev.get("probabilities") or {}
    machine_signal = choice in ("ai", "edited")
    gate_pass = (conf is not None) and (conf >= theta)
    out = {
        "jev_choice": choice,
        "jev_confidence": conf,
        "p_machine": (probs.get("ai", 0) + probs.get("edited", 0)) if probs else None,
        "machine_like": jev.get("machine_like"),
        "gate_pass": gate_pass,
        "editlens_llama": el_score,
        "signals": ["jev"],
        "agreement": None,
        "label": None,
        "advisories": [],
    }
    if el_score is not None:
        out["signals"].append("editlens")
        el_machine = el_score > el_cut
        out["agreement"] = "agree" if el_machine == machine_signal else "disagree"
    if out["agreement"] == "disagree":
        out["label"] = "abstain"
        out["advisories"].append("jev_editlens_disagreement")
    elif gate_pass:
        out["label"] = "machine" if machine_signal else "human"
    else:
        out["label"] = "abstain"
        out["advisories"].append("below_confidence_gate")
    # Advisory: both signals say machine and EditLens is saturated. Measured signature of the
    # human-creative-fiction failure mode, which the two signals cannot otherwise detect.
    if (el_score is not None and machine_signal and el_score >= ADVISORY_EL_SATURATION
            and out["agreement"] == "agree"):
        out["advisories"].append("creative_prose_risk_both_signals_saturated")
    return out


def model_matches(requested: str, echo: str | None) -> bool:
    """True when the served model matches the request. Gateway aliases can drop a '-free'
    suffix or differ by a patch segment, so compare version prefixes."""
    if not echo:
        return True
    req = requested[:-5] if requested.endswith("-free") else requested
    return echo == req or echo.startswith(req) or req.startswith(echo)


def read_inputs(args) -> list[dict]:
    rows: list[dict] = []
    if args.text is not None or args.text_file is not None:
        text = args.text if args.text is not None else Path(args.text_file).read_text(encoding="utf-8")
        rows.append({"id": args.id or "input-1", "text": text})
        return rows
    payload = sys.stdin.read() if args.stdin else Path(args.jsonl).read_text(encoding="utf-8")
    for i, line in enumerate(l for l in payload.splitlines() if l.strip()):
        obj = json.loads(line)
        text = obj.get("text") or ""
        if not text.strip():
            # never spend a request on an empty state; report it instead
            rows.append({"id": str(obj.get("id") or f"row-{i}"), "text": "", "skipped": "empty_text"})
            continue
        rows.append({"id": str(obj.get("id") or f"row-{i}"), "text": text})
    return rows


def frozen_rule_replay(metric: dict) -> dict | None:
    """Replay the frozen rule over the shipped hash-keyed cache. No API calls."""
    cache = HERE / "data" / "selftest_cache.jsonl"
    if not cache.exists():
        return None
    n_scored = emitted = correct = advisories = 0
    for line in cache.open(encoding="utf-8"):
        r = json.loads(line)
        if r["truth"] is None or r["jev_choice"] is None or r["el_llama"] is None:
            continue
        n_scored += 1
        d = decide({"choice": r["jev_choice"], "confidence": r["jev_conf"],
                    "probabilities": r["jev_probs"] or {}}, r["el_llama"],
                   metric["theta"], metric["el_cut"])
        if "creative_prose_risk_both_signals_saturated" in d["advisories"]:
            advisories += 1
        if d["label"] != "abstain":
            emitted += 1
            correct += d["label"] == r["truth"]
    return {"n_scored": n_scored, "emitted": emitted,
            "acc": correct / max(emitted, 1), "advisories": advisories}


def self_test(metric: dict) -> int:
    """Replay the frozen rule only. The expected numbers are the published Tier-1 result."""
    r = frozen_rule_replay(metric)
    if r is None:
        print("missing data/selftest_cache.jsonl")
        return 1
    print(f"self-test on {r['n_scored']} cached Tier-1 texts (hash-keyed cache; no third-party text)")
    print(f"  theta {metric['theta']} | emitted {r['emitted']} | emitted accuracy {r['acc']:.4f}")
    print(f"  creative-prose advisories fired: {r['advisories']}")
    print("  expected (published frozen ensemble): emitted 6492, accuracy 0.7751")
    ok = r["emitted"] == 6492 and abs(r["acc"] - 0.7751) < 0.002
    print(f"  regression check: {'PASS' if ok else 'MISMATCH'}")
    return 0 if ok else 1


def _load_reproduce_module():
    spec = importlib.util.spec_from_file_location("reproduce_tier1", HERE / "scripts" / "reproduce_tier1.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def reproduce(metric: dict) -> int:
    """Run every offline check the repository ships. No API calls."""
    print("reproduction ledger (offline, no API calls)")
    r = frozen_rule_replay(metric)
    if r is None:
        print("  [FAIL] missing data/selftest_cache.jsonl")
        return 1
    ok_rule = r["emitted"] == 6492 and abs(r["acc"] - 0.7751) < 0.002
    print(f"  [{'ok' if ok_rule else 'FAIL'}] frozen rule replay: emitted {r['emitted']}, "
          f"accuracy {r['acc']:.4f}, advisories {r['advisories']}")
    mod = _load_reproduce_module()
    diffs, _S, _V = mod.check_summary_and_verdicts(HERE)
    ok_tables = not diffs
    detail = "exact match" if ok_tables else f"{len(diffs)} mismatch(es)"
    print(f"  [{'ok' if ok_tables else 'FAIL'}] tier-1 summary and M1-M5 vs shipped JSONs: {detail}")
    for d in diffs[:10]:
        print(f"      - {d}")
    adiffs = mod.check_headline_aucs(HERE)
    ok_aucs = not adiffs
    detail = "exact match" if ok_aucs else f"{len(adiffs)} mismatch(es)"
    print(f"  [{'ok' if ok_aucs else 'FAIL'}] headline slice AUCs vs pinned anchors: {detail}")
    for d in adiffs[:10]:
        print(f"      - {d}")
    ok = ok_rule and ok_tables and ok_aucs
    print(f"=> {'REPRODUCED' if ok else 'NOT REPRODUCED'}")
    return 0 if ok else 1


def read_answers(path: Path) -> list[dict]:
    rows = []
    for i, line in enumerate(l for l in path.read_text(encoding="utf-8").splitlines() if l.strip()):
        o = json.loads(line)
        rows.append({"id": str(o.get("id") or f"row-{i}"), "choice": o.get("choice"),
                     "confidence": o.get("confidence"), "probabilities": o.get("probabilities") or {},
                     "editlens_llama": o.get("editlens_llama")})
    return rows


def replay_answers(args, metric: dict) -> int:
    """Apply the frozen rule to stored answers. No API calls."""
    rows = read_answers(Path(args.answers))
    out_rows = []
    labels: dict = {}
    for r in rows:
        if not r["choice"]:
            rec = {"id": r["id"], "label": "abstain", "advisories": ["missing_choice"], "error": None}
        elif r["choice"] not in ("human", "ai", "edited"):
            rec = {"id": r["id"], "label": "abstain", "advisories": ["unknown_choice"], "error": None}
        else:
            d = decide({"choice": r["choice"], "confidence": r["confidence"],
                        "probabilities": r["probabilities"]}, r["editlens_llama"],
                       metric["theta"], metric["el_cut"])
            rec = {"id": r["id"], **d, "error": None}
        rec["n_chars"] = None
        out_rows.append(rec)
        labels[rec["label"]] = labels.get(rec["label"], 0) + 1
    out_rows.sort(key=lambda r: r["id"])
    text = "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in out_rows)
    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    print(f"# {len(out_rows)} stored answers | labels {labels} (offline replay, no API calls)", file=sys.stderr)
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Machine-origin triage for text (Jev + optional EditLens).")
    ap.add_argument("--text")
    ap.add_argument("--text-file")
    ap.add_argument("--id", default=None, help="id for --text/--text-file mode")
    ap.add_argument("--jsonl", help='batch input: one {"id": ..., "text": ...} per line')
    ap.add_argument("--stdin", action="store_true", help="read the batch JSONL from stdin")
    ap.add_argument("--out", help="write JSONL verdicts here (default: stdout)")
    ap.add_argument("--editlens-scores", help='JSONL {"id": ..., "score": ...} to join on id')
    ap.add_argument("--metric", default=str(DEFAULT_METRIC))
    ap.add_argument("--endpoint", default="direct", choices=["direct", "zen"])
    ap.add_argument("--model", default=None, help="model id; defaults per endpoint")
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--no-machine-like", action="store_true")
    ap.add_argument("--answers", help='offline replay: JSONL {"id": ..., "choice": ..., "confidence": ..., "probabilities": {...}, "editlens_llama": ...}')
    ap.add_argument("--reproduce", action="store_true", help="run all offline reproduction checks")
    ap.add_argument("--self-test", action="store_true", help="replay the frozen rule on cached data")
    ap.add_argument("--strict-model", action="store_true",
                    help="exit 4 when the served model differs from --model")
    args = ap.parse_args()

    metric = load_metric(Path(args.metric))
    if args.reproduce:
        return reproduce(metric)
    if args.self_test:
        return self_test(metric)
    if args.answers:
        return replay_answers(args, metric)
    if not (args.text or args.text_file or args.jsonl or args.stdin):
        ap.error("provide --text, --text-file, --jsonl, --stdin or --answers (or --reproduce / --self-test)")

    endpoint = DIRECT_ENDPOINT if args.endpoint == "direct" else ZEN_ENDPOINT
    model = args.model or ("jev-1.13.0" if args.endpoint == "direct" else "jev-1.13-free")
    key = get_key(endpoint)
    rows = read_inputs(args)
    el_scores = {}
    if args.editlens_scores:
        for line in Path(args.editlens_scores).read_text(encoding="utf-8").splitlines():
            if line.strip():
                o = json.loads(line)
                el_scores[str(o.get("id"))] = o.get("score")

    lock = threading.Lock()
    out_rows: list[dict] = []
    usage_in = usage_out = 0
    lat: list[int] = []

    def work(r):
        nonlocal usage_in, usage_out
        if r.get("skipped"):
            with lock:
                out_rows.append({"id": r["id"], "label": None, "advisories": [r["skipped"]],
                                 "n_chars": 0, "error": None})
            return
        t0 = time.time()
        j = call_jev(r["text"], key, endpoint, model, ask_machine_like=not args.no_machine_like)
        ms = int((time.time() - t0) * 1000)
        drifted = False
        if j.get("ok"):
            u = j.get("usage") or {}
            with lock:
                usage_in += int(u.get("input_tokens") or 0)
                usage_out += int(u.get("output_tokens") or 0)
            drifted = not model_matches(model, j.get("model_echo"))
        d = decide(j, el_scores.get(r["id"]), metric["theta"], metric["el_cut"]) if j.get("ok") else {
            "label": "abstain", "advisories": ["request_failed"], "error": j.get("error")}
        rec = {"id": r["id"], "n_chars": len(r["text"]), "label": d["label"],
               "model_requested": model, "endpoint": args.endpoint, "latency_ms": ms, **d}
        if j.get("ok"):
            rec["model_echo"] = j.get("model_echo")
            if drifted:
                rec["advisories"] = list(rec["advisories"]) + ["model_drift"]
        with lock:
            out_rows.append(rec)
            lat.append(ms)

    with ThreadPoolExecutor(max_workers=max(1, args.workers)) as ex:
        list(ex.map(work, rows))

    out_rows.sort(key=lambda r: r["id"])
    text_out = "".join(json.dumps(r, ensure_ascii=False) + "\n" for r in out_rows)
    if args.out:
        Path(args.out).write_text(text_out, encoding="utf-8")
    else:
        sys.stdout.write(text_out)
    ok = sum(1 for r in out_rows if "error" not in r)
    labels = {}
    for r in out_rows:
        labels[r["label"]] = labels.get(r["label"], 0) + 1
    print(f"# {len(out_rows)} texts | ok {ok} | labels {labels} | "
          f"median {statistics.median(lat) if lat else 0:.0f} ms | "
          f"tokens in {usage_in:,} out {usage_out:,} | "
          f"est ${usage_in / 1e6 * 0.042:.4f}", file=sys.stderr)
    n_drift = sum(1 for r in out_rows if "model_drift" in (r.get("advisories") or []))
    if n_drift:
        serveds = sorted({str(r.get("model_echo")) for r in out_rows
                          if "model_drift" in (r.get("advisories") or [])})
        print(f"# WARNING: the served model differs from {model!r}: {', '.join(serveds)} "
              f"({n_drift} responses)", file=sys.stderr)
    if ok == 0:
        return 3
    if args.strict_model and n_drift:
        return 4
    return 0


if __name__ == "__main__":
    sys.exit(main())
